### ISSUE TITLE
System Resources

### ISSUE THREAD

**Issue by Palanikannan1437** [Aayush9029/Native-Youtube#12]
As per your claims on reddit, the app didn't use 30x less resources.
(I use a MBP 2020 Intel)
on youtube safari, the resources taken for a normal 720p video were 
CPU by youtube.com - on avg 8-10%
CPU by safari - 0.3-2%
On the otherhand,
CPU by Native Youtube - 2-5%
CPU by mpv - 30-60% !

Memory taken by youtube.com and mpv were almost same

**Comment by insomnia-creator** [comment]
True. The system resource thing will be fixed as the app further progresses, keep in mind that this is pre-PRE-alpha. It's in no usable state right now but it will get better as time passes.


Just patiently wait for now.

**Comment by Palanikannan1437** [comment]
> True. The system resource thing will be fixed as the app further progresses, keep in mind that this is pre-PRE-alpha. It's in no usable state right now but it will get better as time passes.
> 
> Just patiently wait for now.


Oh okay, since the creator said it uses 30x less resources than safari, I thought he released the same version. But hats off to the guy if he makes that possible anytime soon. Will wait for the stable release.

**Comment by Aayush9029** [comment]
> True. The system resource thing will be fixed as the app further progresses, keep in mind that this is pre-PRE-alpha. It's in no usable state right now but it will get better as time passes.

> Just patiently wait for now.


This sums things up!

Currently app stability and usability is top priority
App optimization process for this release will begin after fixing those issues.
