### ISSUE TITLE
Search UI overflows

### ISSUE THREAD

**Issue by Aayush9029** [Aayush9029/Native-Youtube#15]
![Screen Shot 2021-05-23 at 10 01 00 PM](https://user-images.githubusercontent.com/43297314/119286478-6c756c00-bc12-11eb-8e94-7026e49d7f3d.png)

**Comment by Aayush9029** [comment]
*Reminder*

Add a GRID Layout

**Comment by insomnia-creator** [comment]
Add padding to the titlebar.
