### ISSUE TITLE
Icon is way bigger than other icons

### ISSUE THREAD

**Issue by Human79** [Aayush9029/Native-Youtube#2]
Whenever you have time please reduce the size of the icon. 

![Screen Shot 2021-05-20 at 8 55 15 PM](https://user-images.githubusercontent.com/84245065/119006352-ece76300-b9ad-11eb-9b39-e4a5e68cb700.png)

Thanks.

**Comment by insomnia-creator** [comment]
I've created a [pull request](https://github.com/Aayush9029/Native-Youtube/pull/7) to address this issue.
 Honestly on my end this looks a million times better already.
<h2>This looks wayyyy better</h2>

<img width="900" alt="Screenshot 2021-05-21 at 10 49 22 AM" src="https://user-images.githubusercontent.com/69950985/119085895-34a7d200-ba22-11eb-82cb-f71b4707c12d.png">

**Comment by Aayush9029** [comment]
I've merged the request and will update the AppIcon from xcassets soon.


Thanks a lot!
