### ISSUE TITLE
ADDITION: Installer. Yes an installer.

### ISSUE THREAD

**Issue by insomnia-creator** [Aayush9029/Native-Youtube#22]
I made one DMG installer for Native-Youtube

How is this different from normal installers? Well... The difference is that compared to normal installers which need to be updated every single releases this one runs on an sh file... Basically the code for this is in reality just installing from my fork of install.sh and it needs no updating(i can just change the fork thing upon release so it works with all releases, or you can as well technically.

https://github.com/insomnia-creator/Native-Youtube/raw/main/Native-Youtube-installer.dmg

**Comment by Aayush9029** [comment]
404

**Comment by insomnia-creator** [comment]
Oh I must have removed it in the pr for install.sh, I'll make a new pr to fix this.
