### ISSUE TITLE
Play Music option creates multiple streams

### ISSUE THREAD

**Issue by adandekar-sfdc** [Aayush9029/Native-Youtube#27]
As there are two options to play, with video and just music. I played a song with "Just Music" option and then after some time I played the same song again ("Just Music"). it is adding multiple streams in the global music navigation menu. 

![Screen Shot 2021-06-21 at 11 00 31 AM](https://user-images.githubusercontent.com/58186826/122807446-737ab300-d280-11eb-8c2c-25ab5b247337.png)

Is this Expected?

When I play "Just Music" is there a way to have a single stream like (Now Playing) overwriting the previous one. (may be a feature request)

**Comment by insomnia-creator** [comment]
2 same instances of shell process. Might create a PR to resolve this.

**Comment by chaoticbit** [comment]
yes exactly! I mean there should be always one process for the Currently Playing video/music.

Thanks for noticing. Will be looking forward to the fix
@Aayush9029

**Comment by Aayush9029** [comment]
I'm very busy this summer, After August I'll might have a little more time to work on this. I'll be revamping some UI and processes. And maybe it will go to beta version. 🤞
*this is still in alpha version*



Meanwhile, I'll try to look at pull request from time to time and merge a working (well documented) ones.

**Comment by insomnia-creator** [comment]
Also I'm noticing this

Process() does sometimes does NOT run brew installed commands. This killed the life of me while making M-GUI(reason why I had to switch to Java). Just noticed the thing in swift.

So that's why some people aren't able to play videos. I might look into ways and make a PR for one.

**Comment by insomnia-creator** [comment]
This will be created into a separate issue.

**Comment by Aayush9029** [comment]
> Also I'm noticing this
> 
> Process() does sometimes does NOT run brew installed commands. This killed the life of me while making M-GUI(reason why I had to switch to Java). Just noticed the thing in swift.
> 
> So that's why some people aren't able to play videos. I might look into ways and make a PR for one.

This has been fixed with the 3.0 update :D

**Comment by Aayush9029** [comment]
Will work on killing the process before running it later this week. 

App should be functional and should work quite well on m1 Macs now.

**Comment by Aayush9029** [comment]
FIXED with alpha 4.0 release

**Comment by Aayush9029** [comment]
> yes exactly! I mean there should be always one process for the Currently Playing video/music.
> 
> Thanks for noticing. Will be looking forward to the fix
> @Aayush9029

Done.
