### ISSUE TITLE
 Videos and Music unable to play.

### ISSUE THREAD

**Issue by insomnia-creator** [Aayush9029/Native-Youtube#28]
This is most likely an issue with Process() and bash or zsh unable to identify homebrew commands on some computers. Will need to see how well this goes with an exectuable. Meanwhile I'll experiment with Xcode to see what is the best way. 

I'm getting command not found when I try to run the exact same code on AppDelegate, 

bash: mpv command not found

**Comment by Aayush9029** [comment]
Should work!
Working on m1 Mac 11.5 (20G71)

**Comment by insomnia-creator** [comment]
Nope not working, 

https://user-images.githubusercontent.com/69950985/126948321-630409da-a80d-4078-88a6-8b4a66dac373.mov

I don't know why this isn't working, but it might be an issue due to the app getting Sandboxed.

**Comment by insomnia-creator** [comment]
Also Setup.py aint working

**Comment by Aayush9029** [comment]
What’s the error?

can you show output for ~/.mubbi/config.json

*hide the api key*

**Comment by insomnia-creator** [comment]
Traceback (most recent call last):
  File "/Users/it/setup.py", line 10, in <module>
    auth_token = args[1]
IndexError: list index out of range
➜  ~

**Comment by Aayush9029** [comment]
> Traceback (most recent call last):
> File "/Users/it/setup.py", line 10, in
> auth_token = args[1]
> IndexError: list index out of range
> ➜ ~

Make sure to pass oauth token as second argument, feel free to run install.sh again it won’t install dependencies if they’re already installed

**Comment by insomnia-creator** [comment]
Not working still
<img width="1214" alt="Screenshot 2021-07-26 at 12 58 46 PM" src="https://user-images.githubusercontent.com/69950985/126949774-5a934390-91ba-4680-98d1-5a6a0cd2ca93.png">

**Comment by Aayush9029** [comment]
Ok I’ll look into this more, perhaps create a log console tomorrow!

**Comment by insomnia-creator** [comment]
The process is quite strenuous right now, like setup.py and all. Just use shell scripting for configs

**Comment by Aayush9029** [comment]
Just outta curiosity what shell do you run?

is it for fish? Or good ol zsh? Do you know?

@insomnia-creator

**Comment by insomnia-creator** [comment]
I run oh-my-zsh.(zsh)

And can we please connect on discord, I would like to try and find a solution for why it isnt working.

**Comment by insomnia-creator** [comment]
sent you a request

**Comment by insomnia-creator** [comment]
Closed by commit 464b7c3cb97e56005745c6dde05d1d7b4d3001fd
