### ISSUE TITLE
Video player controls

### ISSUE THREAD

**Issue by Aayush9029** [Aayush9029/Native-Youtube#45]
Known Issue.
---

Play pause
Next, forward
mute
And stopping playback doesn't work on the new video player

![Screen Shot 2021-11-23 at 4 05 32 PM](https://user-images.githubusercontent.com/43297314/143126082-66f2769f-a65e-44ff-bfdc-f3f7ac969fa5.png)

![Screen Shot 2021-11-23 at 4 05 24 PM](https://user-images.githubusercontent.com/43297314/143126072-7f2902fd-f382-4961-9061-9577e47556d4.png)

---

Guess is since i'm passing the youtubeVideo as let and var instead of @Statevariables swiftUI is acting weird.

*Will take a look at it this winter, video playback works and this is a huge achievement.*

---

**Comment by ErrorErrorError** [comment]
There should also probably be an option for seek bar if that's possible. I might take a shot and see if I can implement it!
