### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by brak265** [Aayush9029/Native-Youtube#47]
I'm not sure if this is the correct place to make this comment, but I just wanted to suggest adding to the app the ability to link your device to another device in your home (like the way you can control the YouTube app on a smart tv using a Chrome browser in macOS on the same WiFi).  Using your laptop as a YouTube remote is a really useful feature, and it seems like only the Chrome browser supports it, at least on macOS.  It would be great if this tool had that feature added. Unfortunate if it's something only Google can control.  Airplay processes the video on your device, or at least it does if you're screen sharing, so having your laptop just tell the tv remotely to load a video on the YouTube app is useful.

**Comment by Aayush9029** [comment]
This is a native YouTube player not a remote!
I have no plans on adding chromecast support.

I have plans to support AirPlay though!
