### ISSUE TITLE
Cannot play video

### ISSUE THREAD

**Issue by insomnia-creator** [Aayush9029/Native-Youtube#6]
Cannot play video(API key inputted).

Also API key box too small.

Also the icon is too big, (I'll make one if I can),

The app cannot play videos no matter what I do, right click or anything.

**Comment by theakshat1** [comment]
+1 I added api and search is also working but I am clicking on video and it isn't playing

Edit: Mac M1

**Comment by EtenE10** [comment]
+1 
Same - added API in the little tiny box - search ok. 
The app cannot play videos
Reinstalled homebrew, mpv youtube-dl
on mac M1

**Comment by Palanikannan1437** [comment]
The app can search but is not able to play any videos no matter what I do(Big Sur 11.3.1 intel mac)

**Comment by Aayush9029** [comment]
New release fixes this issue, with bigger input box that never closes and stays on the bottom of the playlist bar page.

**Comment by theakshat1** [comment]
Still not able to play videos on Mac m1 

I reinstalled everything again

**Comment by insomnia-creator** [comment]
+1 Reinstalled everything, Still can't play video.

M1 macbook pro
See: https://free-download.amongusgame.net/VKqcNVfj

**Comment by Aayush9029** [comment]
Can you verify is mpv and or YouTube-dl  is working for you?

type 

> mpv

> YouTube-dl 

To see if they seem to work

**Comment by theakshat1** [comment]
<img width="1145" alt="Screenshot 2021-05-24 at 6 30 42 AM" src="https://user-images.githubusercontent.com/66463310/119283145-bafa2900-bc59-11eb-8506-2f1d8218dc6f.png">

I guess they are good

**Comment by aslak01** [comment]
Is there a log accessible anywhere that shows http errors and stuff? Nothing happens when I press any button, and I'm not sure my api key is working (had some problem with it the Kodi plugin, but google dev console doesn't report anything wrong with it).

**Comment by insomnia-creator** [comment]
Don't know. But once I learn swift I will try and continue this project.

**Comment by Thelevithan** [comment]
@Aayush9029 can u reopen this issue

After latest update also it not able to play videos
