### ISSUE TITLE
[Feature Request] Allow listening to videos in the background without IINA

### ISSUE THREAD

**Issue by erikbdev** [Aayush9029/Native-Youtube#60]
Hello,

As we talked about adding support to play videos in the background, aka background audio, without the need of IINA. One approach would be implementing our own version of AVPlayer, which includes having to implement a decoder for webm + VP9 since AVFoundation has no implementation of that.

Another way we could use is using VLCKit which would help.

However, I was thinking we could use YouTubePlayerKit and have a video play but hide the window to  simulate "background audio" playback.

These are just ideas on how we could implement.

**Comment by Aayush9029** [comment]
> However, I was thinking we could use YouTubePlayerKit and have a video play but hide the window to simulate "background audio" playback.

if the system resource usage is minimal this might be a valid option! Not sure how macOS will handle the "hidden view" playing audio. Will it still render the video and use GPU? or... *Further experimentation is required :)*

VLCKit would be ideal, as that'll take the least amount of resources. IINA doesn't use a lot of resource but is definitely annoying (clunky) for music playback. 

`youtube-dl --get-url -f 251 "https://www.youtube.com/watch?v=sAn7baRbhx4"`
Here's an example of extracting the audio url 

I tried playing the output url using..
- IINA ✅
- ffplay✅
- QuickTime ❌
- vlc ✅
- safari ❌
- firefox ✅

**Comment by Aayush9029** [comment]
<img width="344" alt="AShot-2022 02 24-01 13 18@2x" src="https://user-images.githubusercontent.com/43297314/155468437-1485b970-b793-4b2c-a8bb-1e1ea44d0a16.png">

Wait IINA's music player isn't that bad! Only if there was a way to toggle this when invoking the command!
