### ISSUE TITLE
missing features

### ISSUE THREAD

**Issue by vtolstov** [Aayush9029/Native-Youtube#61]
* Can you add ability to close the app?
* Can you add playlists support? If you add it the app will be excellent!

**Comment by Aayush9029** [comment]
> Can you add ability to close the app?

The pop over it self or the video? You can press command + q (for now) to close the popover. 

> Can you add playlists support? 

Sure i'lll add that in my to-do!

**Comment by vtolstov** [comment]
1) thank you, may be will be good to add quit button in some place?
2) do you have some roadmap when you will be ready to publish playlist support ?:)

**Comment by Aayush9029** [comment]
> do you have some roadmap when you will be ready to publish playlist support ?:)

It's as simple as adding an input box in settings page :D

I'll release the patch along side other bug fixes and cool features `ErrorErrorError` has added in the next release!

A week max!

**Comment by vtolstov** [comment]
great!

**Comment by Aayush9029** [comment]
Done: https://github.com/Aayush9029/NativeYoutube/commit/6ee36f4982eda416a82837183fc90e8fa5cd7208

To quit the app you'll have to stick with command + q.

I have to intention of adding another button to the UI, maybe in the future

https://github.com/Aayush9029/NativeYoutube/releases/tag/v2.2.3


Note: the build is not notarized you'll have to ctrl + click or use `xattr -c`

**Comment by vtolstov** [comment]
Does it possible to load all user playlist in dedicated "tab/button" to allow to start playing from it?

**Comment by Aayush9029** [comment]
> Does it possible to load all user playlist in dedicated "tab/button" to allow to start playing from it?

If IINA adds support for playlist ill add it!!

Loading and Adding songs to queue and playing is possible but it'll be super finicky; IINA doesn't have a dedicated api for play and pause (remotely)!

**Comment by vtolstov** [comment]
about playlist: IINA already supports playlist, does it possible to get playlist from youtube via api, get all items from it and add to IINA playlist?
