### ISSUE TITLE
SwiftTube - API Library for YouTube

### ISSUE THREAD

**Issue by leogdion** [Aayush9029/Native-Youtube#63]
Hey @Aayush9029 

I built [a SwiftPackage specifically for the YouTube API](https://github.com/brightdigit/SwiftTube). I would love to get some feedback on it and see if it would be helpful to you.
Let me know.

**Comment by Aayush9029** [comment]
Hi 👋 @leogdion 

Amazing work! Looks like you're missing LICENSE.md

I'm working on an iOS app that interacts with YouTube api and I think this library will be a great fit!

Again Amazing work!
