### ISSUE TITLE
Sign using new Certificate

### ISSUE THREAD

**Issue by Aayush9029** [Aayush9029/Native-Youtube#65]
Build and Release New Version of Native Youtube using different certificate. My old certificate was revoked.

> Will wait for macOS Ventura to be officially released. So I can ditch hacky SwiftUI implementations.

**Comment by blakeperdue** [comment]
Any update now that Venture has been officially released? Thanks!

**Comment by Aayush9029** [comment]
> Any update now that Venture has been officially released? Thanks!

Will wait for exam season to be over at uni :)

I'm considering re-writing the entire thing from scratch for v3.

**Comment by Aayush9029** [comment]
[NativeYoutube.zip](https://github.com/Aayush9029/NativeYoutube/releases/download/v2.2.3.1/NativeYoutube.zip)
