### ISSUE TITLE
Jarring scrolling

### ISSUE THREAD

**Issue by electr1fy0** [Aayush9029/Native-Youtube#72]
Due to the sliding animation on mouse hover, it looks terrible when scrolling and by itself there's too much motion just for moving the mouse.
I'll suggest having the animation trigger only when selecting a video by single clicking which as of now does nothing.

**Comment by Aayush9029** [comment]
Sounds about right.

**Comment by electr1fy0** [comment]
**A few observations after testing it:**
1. Scrolling is smooth and flawless.
2. Multiple videos can be selected simultaneously (Video doesn't get deselected upon selecting another one).
3. Double click seems to be broken.

**Comment by Aayush9029** [comment]
> 2. How do you think we should handle this? 

Hide after a delay or **Show detail view** ie: larger thumbnail + actions, description and video info...

**Comment by electr1fy0** [comment]
**Selecting a video to just see slightly more of title isn't particularly useful imo.**
<br> <br>

**Few suggestions:**
1. Actions should be listed inside a secondary click (the way it is right now) in order to avoid clutter.
2. About the title:
	_1. The font size of the **title** could be **smaller** as to accommodate more of the title in the list.  
	2. The text where the mouse pointer is hovering should just scroll in a loop to be able to see truncated title.
	3. Slightly wider aspect ratio of the menu bar window._
3. About the thumbnail:
	_1. A slightly smaller thumbnail. (makes the list thinner). Saved horizontal space should go for ...more space for the title and saved vertical space goes for more videos in sight.
	2. It should contain video length chip as well at the bottom right corner._
4. About selecting a video:
	_1. Current selection should get deselected upon selecting another video.
	2. I'm not exactly sure what info should be displayed but I'm leaning towards the thumbnail expanding to full width (with padding of course) a very quick in and out animation just below the selected row item so the row just vertically expands with a larger thumbnail._
5. Description could be a secondary click menu item that displays the description upon mouse hover. 
<br>

_I don't even know how much of this is even possible but these are just ideas._
<br><br>
**Some OT suggestions:**
1. Launching the app, let's say via Finder or Raycast should activate the window as well, preferably with Search bar highlighted.
2. Playing a video should hide the list automatically.

**Comment by Aayush9029** [comment]
Sounds like a plan!
