### ISSUE TITLE
Ability to go full screen in the app's media player

### ISSUE THREAD

**Issue by electr1fy0** [Aayush9029/Native-Youtube#75]
(self explanatory, again)

**Comment by Aayush9029** [comment]
Check IINA under player settings if you want something immersive.

> I have no plans on making a full screen player (by default).
> NativeYoutube is supposed to feel light and provide a non-immersive experience.

**Comment by Aayush9029** [comment]
However I'm not opposed to one, forking the repo and maintaining a more immersive version of NY.

- Cheers

**Comment by electr1fy0** [comment]
My problem with IINA is the super slow loading of any video despite changing it to YT-DLP but I get your point.
Cheers!
