### ISSUE TITLE
Cannot input API Key

### ISSUE THREAD

**Issue by nathom** [Aayush9029/Native-Youtube#8]
I can't figure out where to paste the API key. When I open the app, I see the following screen:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/74019033/119085775-37221180-b9b9-11eb-911a-1f92618e6ed7.png">

Clicking the `Save API Key` button does nothing.

System:
- 2015 15" MacBook Pro
- macOS 11.3.1

**Comment by insomnia-creator** [comment]
There is a tiny textbox next to the Save API Key button
<img width="31" alt="Screenshot 2021-05-21 at 10 51 31 AM" src="https://user-images.githubusercontent.com/69950985/119086039-818ba880-ba22-11eb-8da0-095d818e3934.png">

^^^This one


So just click it, (you'll see a little text cursor) and command+v into it.

**Comment by thisbansal** [comment]
2019 15" MacBook Pro v11.3.1
Exactly the same issue. 
Unable to save keys because the textbook is so tiny that I'm not able to click on it.
Can we make is bigger? or perhaps have the option under preferences?

**Comment by thisbansal** [comment]
> Unable to save keys because the textbook is so tiny that I'm not able to click on it.

Just got lucky and able to enter the text and save the API; I'll be testing this app right now!
But can we really make it bigger or something?

**Comment by insomnia-creator** [comment]
I have no idea how swift works since I'm primarily focused on web development.

**Comment by Thelevithan** [comment]
Can someone please tell me I entered the api and the search is also working perfectly but I can't play videos idk why

**Comment by Aayush9029** [comment]
The "side translucent bar" view should be re-scalable.


I will make the min width a bit bigger to fix this issue.
