### ISSUE TITLE
Subscriptions Videos

### ISSUE THREAD

**Issue by Ramalama2** [Aayush9029/Native-Youtube#80]
Hi, is it possible somehow, to view subscriptions only, simply sorted by newest.
Because with playlists, its a bit stupid somehow for me, to go into youtube first, add all the newest videos that i subscribed to, to an playlist etc...
Im wondering that no one else requested this.

Otherwise the app is working really great! Just a bit stupid in my case with subscriptions xD

Thanks Aayush for this app anyway!!

**Comment by Aayush9029** [comment]
I can't promise anything, but I'll definitely look into it!

Thanks a lot for the support ❤️ 
You da best

**Comment by Ramalama2** [comment]
https://github.com/Elijas/auto-youtube-subscription-playlist-2

Im using this now as workaround, works actually good and a great solution in the meantime for everyone that wish his subscriptions either.
Just one thing to this, you have to tick in the playlist sorting options, "new videos by release ontop" and nativeplayer will show it then the same way.

Thx again aayush!
