### ISSUE TITLE
[Request] Compatibility with 10.15+

### ISSUE THREAD

**Issue by jebediah2** [Aayush9029/Native-Youtube#81]
Hey would you be able to compile a version that's compatible with 10.15 and up?

**Comment by Aayush9029** [comment]
Nope

**Comment by anka-213** [comment]
@Aayush9029 Forgive my ignorance, but may I ask why? Can't you just change `MACOSX_DEPLOYMENT_TARGET` or do you depend on some newer API functions that are only available in MacOS 13 and up?

**Comment by truong-kyle** [comment]
I believe he uses MenuBarExtra, which is a MacOS 13+ API

**Comment by anka-213** [comment]
@truong-kyle I see, thanks!
