### ISSUE TITLE
"Native Youtube" cannot be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by Terabyte1385** [Aayush9029/Native-Youtube#9]
<img width="755" alt="Screenshot 2021-05-21 at 09 26 22" src="https://user-images.githubusercontent.com/78782971/119092224-d7f2ea00-ba16-11eb-9dec-cb6ef045e0ae.png">

What do I do?

**Comment by pabpereza** [comment]
Go to System Preferences->Security & Privacy->General Tab. In this windows you will allow third party application execution.

**Comment by insomnia-creator** [comment]
Hold the control key and click the app from finder, then click allow.

**Comment by Aayush9029** [comment]
I'll have to notarize the next release.

**Comment by insomnia-creator** [comment]
No it still happens. Still need to control-click run.

**Comment by derickke12** [comment]
Me too how do i open it

**Comment by Aayush9029** [comment]
@derickke12 

> Hold the control key and click the app from finder, then click allow.
